//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace JogosDeGaragemModel.Archery
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ArcheryEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ArcheryEntities object using the connection string found in the 'ArcheryEntities' section of the application configuration file.
        /// </summary>
        public ArcheryEntities() : base("name=ArcheryEntities", "ArcheryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ArcheryEntities object.
        /// </summary>
        public ArcheryEntities(string connectionString) : base(connectionString, "ArcheryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ArcheryEntities object.
        /// </summary>
        public ArcheryEntities(EntityConnection connection) : base(connection, "ArcheryEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StatusJogo> StatusJogos
        {
            get
            {
                if ((_StatusJogos == null))
                {
                    _StatusJogos = base.CreateObjectSet<StatusJogo>("StatusJogos");
                }
                return _StatusJogos;
            }
        }
        private ObjectSet<StatusJogo> _StatusJogos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StatusJogos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatusJogos(StatusJogo statusJogo)
        {
            base.AddObject("StatusJogos", statusJogo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArcheryModel", Name="StatusJogo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatusJogo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StatusJogo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="pontuacao">Initial value of the Pontuacao property.</param>
        /// <param name="flechas">Initial value of the Flechas property.</param>
        /// <param name="nivel">Initial value of the Nivel property.</param>
        public static StatusJogo CreateStatusJogo(global::System.Int32 id, global::System.String email, global::System.Int32 pontuacao, global::System.Int32 flechas, global::System.Int32 nivel)
        {
            StatusJogo statusJogo = new StatusJogo();
            statusJogo.Id = id;
            statusJogo.Email = email;
            statusJogo.Pontuacao = pontuacao;
            statusJogo.Flechas = flechas;
            statusJogo.Nivel = nivel;
            return statusJogo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pontuacao
        {
            get
            {
                return _Pontuacao;
            }
            set
            {
                OnPontuacaoChanging(value);
                ReportPropertyChanging("Pontuacao");
                _Pontuacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pontuacao");
                OnPontuacaoChanged();
            }
        }
        private global::System.Int32 _Pontuacao;
        partial void OnPontuacaoChanging(global::System.Int32 value);
        partial void OnPontuacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Flechas
        {
            get
            {
                return _Flechas;
            }
            set
            {
                OnFlechasChanging(value);
                ReportPropertyChanging("Flechas");
                _Flechas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flechas");
                OnFlechasChanged();
            }
        }
        private global::System.Int32 _Flechas;
        partial void OnFlechasChanging(global::System.Int32 value);
        partial void OnFlechasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Nivel
        {
            get
            {
                return _Nivel;
            }
            set
            {
                OnNivelChanging(value);
                ReportPropertyChanging("Nivel");
                _Nivel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Nivel");
                OnNivelChanged();
            }
        }
        private global::System.Int32 _Nivel;
        partial void OnNivelChanging(global::System.Int32 value);
        partial void OnNivelChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ArcheryModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="pontuacaoMaximaJogo">Initial value of the PontuacaoMaximaJogo property.</param>
        /// <param name="pontuacaoTotal">Initial value of the PontuacaoTotal property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nome, global::System.String email, global::System.Int32 pontuacaoMaximaJogo, global::System.Int32 pontuacaoTotal)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Nome = nome;
            usuario.Email = email;
            usuario.PontuacaoMaximaJogo = pontuacaoMaximaJogo;
            usuario.PontuacaoTotal = pontuacaoTotal;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PontuacaoMaximaJogo
        {
            get
            {
                return _PontuacaoMaximaJogo;
            }
            set
            {
                OnPontuacaoMaximaJogoChanging(value);
                ReportPropertyChanging("PontuacaoMaximaJogo");
                _PontuacaoMaximaJogo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PontuacaoMaximaJogo");
                OnPontuacaoMaximaJogoChanged();
            }
        }
        private global::System.Int32 _PontuacaoMaximaJogo;
        partial void OnPontuacaoMaximaJogoChanging(global::System.Int32 value);
        partial void OnPontuacaoMaximaJogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PontuacaoTotal
        {
            get
            {
                return _PontuacaoTotal;
            }
            set
            {
                OnPontuacaoTotalChanging(value);
                ReportPropertyChanging("PontuacaoTotal");
                _PontuacaoTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PontuacaoTotal");
                OnPontuacaoTotalChanged();
            }
        }
        private global::System.Int32 _PontuacaoTotal;
        partial void OnPontuacaoTotalChanging(global::System.Int32 value);
        partial void OnPontuacaoTotalChanged();

        #endregion

    
    }

    #endregion

    
}
